connexion with dns

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -13,20 +13,23 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
+      - name: Debug Secrets
+        run: echo "EC2_PUBLIC_DNS=${{ secrets.EC2_PUBLIC_DNS }}"
+
       - name: Set up SSH key
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -t rsa ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
+          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_DNS }} > ~/.ssh/known_hosts || echo "Failed to scan keys, proceeding anyway"
 
       - name: Transfer files to EC2
         run: |
-          scp -i ~/.ssh/id_rsa -r * ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/app
+          scp -i ~/.ssh/id_rsa -r * ubuntu@${{ secrets.EC2_PUBLIC_DNS }}:/home/ubuntu/app
 
       - name: Build and run Docker Compose on EC2
         run: |
-          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
             cd /home/ubuntu/app
             docker compose down
             docker compose build
